CREATE TABLE IF NOT EXISTS PROJECT (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    DEADLINE DATE,
    DESCRIPTION LONGTEXT,
    NAME VARCHAR(100) NOT NULL,
    STATUS VARCHAR(20),
    CREATEDAT DATE,
    CREATEDBY VARCHAR(255),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TASK (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    STATUS VARCHAR(255),
    TITLE VARCHAR(255) NOT NULL,
    CREATEDAT DATE,
    CREATEDBY VARCHAR(255),
    PROJECT_ID BIGINT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO PROJECT (ID, NAME, DESCRIPTION, STATUS, DEADLINE, CREATEDBY, CREATEDAT)
VALUES
    (1, 'Sitio Web Corporativo', 'Desarrollo del nuevo sitio web v2', 'Activo', '2025-12-31', 'import_user', '2025-01-01'),
    (2, 'App Movil (ProjectTracker)', 'Lanzamiento de la app nativa', 'Planificado', '2026-03-15', 'import_user', '2025-01-10')
ON DUPLICATE KEY UPDATE
    NAME = VALUES(NAME),
    DESCRIPTION = VALUES(DESCRIPTION),
    STATUS = VALUES(STATUS),
    DEADLINE = VALUES(DEADLINE),
    CREATEDBY = VALUES(CREATEDBY),
    CREATEDAT = VALUES(CREATEDAT);

INSERT INTO TASK (ID, TITLE, STATUS, PROJECT_ID, CREATEDBY, CREATEDAT)
VALUES
    (1, 'Disenar Homepage', 'Completada', 1, 'import_user', '2025-01-02'),
    (2, 'Desarrollar formulario de contacto', 'En Progreso', 1, 'import_user', '2025-01-03'),
    (3, 'Definir API de Tareas', 'Completada', 2, 'import_user', '2025-01-11'),
    (4, 'Testear login de usuario', 'Pendiente', 2, 'import_user', '2025-01-12'),
    (5, 'Tarea Vieja de Prueba', 'Completada', 1, 'admin', '2020-01-01')
ON DUPLICATE KEY UPDATE
    TITLE = VALUES(TITLE),
    STATUS = VALUES(STATUS),
    PROJECT_ID = VALUES(PROJECT_ID),
    CREATEDBY = VALUES(CREATEDBY),
    CREATEDAT = VALUES(CREATEDAT);

ALTER TABLE PROJECT AUTO_INCREMENT = 100;
ALTER TABLE TASK AUTO_INCREMENT = 100;
