{
 "title": "ProjectTracker O11Y",
 "tags": [
  "jakarta-ee",
  "microprofile",
  "project-tracker"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Metrics Endpoint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"project-tracker-metrics\", runtime=\"payara\"}",
     "legendFormat": "Metrics endpoint"
    }
   ]
  },
  {
   "title": "Readiness Probe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"project-tracker-readiness\", runtime=\"payara\"}",
     "legendFormat": "Readiness"
    }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "project_tracker_database_up{job=\"project-tracker-metrics\", runtime=\"payara\"}",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "REST Custom Metrics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(project_tracker_http_requests_total{job=\"project-tracker-metrics\"}[1m])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Metric Samples",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"project-tracker-metrics\", __name__=~\"project_tracker_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"project-tracker-container\"}"
    }
   ]
  }
 ]
}